version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install bandit
  build:
    commands:
      - echo "Running Bandit Static Analysis"
      - bandit -r . > bandit_report.txt || true

artifacts:
  files:
    - bandit_report.txt
