version: 0.2

phases:
  install:
    commands:
      - pip install -r requirements.txt
      - curl -sS https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip -o build-wrapper-linux-x86.zip
      - unzip build-wrapper-linux-x86.zip -d sonar
  pre_build:
    commands:
      - sonar-scanner -Dsonar.projectKey=Chandan2595_job-application-tracker-Dsonar.organization=handan2595 -Dsonar.sources=. -Dsonar.host.url=https://3680f67f4d8737837060cb838f63fe0f08148217
  build:
    commands:
      - pytest tests/test_app.py --maxfail=1 --disable-warnings -q
artifacts:
  files:
    - '**/*'
