version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt || true
      - pip install bandit
  build:
    commands:
      - echo Running Bandit security scan...
      - bandit -r app.py || true
  post_build:
    commands:
      - echo Build complete.
artifacts:
  files:
    - '**/*'
