version: 0.2

phases:
  install:
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - pytest tests/test_app.py --maxfail=1 --disable-warnings -q
artifacts:
  files:
    - '**/*'
