version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install bandit
  build:
    commands:
      - echo "Running Bandit Static Analysis"
      - bandit -r . > bandit-report.txt

artifacts:
  files:
    - bandit-report.txt
