version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Running Static Code Analysis"
      - bandit -r app.py || true
      - echo "Zipping Deployment Package"
      - zip -r deploy-package.zip .
artifacts:
  files:
    - deploy-package.zip
