version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - pytest --maxfail=1 --disable-warnings -q
artifacts:
  files:
    - '**/*'
